print("welcome to the simple multiplication calculator")
print("this calculator multiplies two numbers provided by the user")
first_num=int(input("Enter first number"))
second_num=int(input("Enter second number"))
output=(first_num*second_num)
print(output)
